### ISSUE TITLE
DefaultMediaDensityCutsProbe returning incorrect densities when not centred on origin

### ISSUE THREAD

**Issue by christopherlovell** [SKIRT/SKIRT9#12]
**Description**
When the spatial grid is not centred on the origin `DefaultMediaDensityCutsProbe` forcibly returns results at the origin.

**Reproduce**

Files:
[convert_units.py.txt](https://github.com/SKIRT/SKIRT9/files/3602592/convert_units.py.txt)
[test.ski.txt](https://github.com/SKIRT/SKIRT9/files/3602591/test.ski.txt)

To demonstrate, let's run through the SPH example from the docs. `convert_units.py` translates the `eagle_stars.txt` and `eagle_gas.txt` coordinates and writes them to `test_stars.txt` and `test_gas.txt`

`test.ski`, constructed during the tutorial but updated to build a grid on the translated axes, uses these output files to run SKIRT

`skirt -i . test.ski`

We can then run

`pts plot_density_cuts . --prefix=test`

to visualise the FITS output. When any axis is translated away from the origin, the projection along that axis plane is still centred on the origin.

**Data**
`eagle_stars.txt` and `eagle_gas.txt`, obtained [here](http://www.skirt.ugent.be/version9/_tutorial_hydro_s_p_h.html)

**Comment by christopherlovell** [comment]
I have proposed an update here:

https://github.com/christopherlovell/SKIRT9/commit/54773e53df7a2c321e2351ed429ab963c45c0565

This fixes the density FITS files. But I'm unsure if this breaks anything else. Could anyone suggest some further tests?

**Comment by christopherlovell** [comment]
Got it, sorry for the misunderstanding. This would be useful, especially for cosmological zoom simulations, since the box is never centred on the origin, which makes this default test (as well as the optical depth test in SpatialGridConvergenceProbe) unnecessary. 

I will update the PR with a separate probe (PlanarMediaDensityCutsProbe) for this use case.

**Comment by petercamps** [comment]
@christopherlovell I merged your proposed planar probe. I'm thinking though that it would be nice to allow specifying the intersection point of the three cut planes (i.e. three coordinates). That way, users can request multiple arbitrary cuts by including multiple probes. The only drawback is that, for your use case, the user must calculate the midway point of the spatial grid and enter it in the ski file (I don't see a way to avoid that without introducing a Boolean option, which seems overkill). 

What do you think? And would you be up to implementing this? Otherwise I can do it.

**Comment by christopherlovell** [comment]
Agreed, would make it much more flexible. Perhaps it could use the grid centres by default if no values are provided by the user? This way you could carry out 'scans' through the medium by just looping over a single axis value.

Happy to have a go at implementing this.

**Comment by petercamps** [comment]
@christopherlovell Because I wanted the default probes to use the same code as the arbitrary planar probes, a substantial refactoring was needed, which is why I implemented this myself. Sorry if this causes any inconvenience. The result is an extension of your contributed planar probe that allows specifying the position of the cuts. See pull request #25 and the documentation of the classes for details.

**Important note**
Unfortunately, there is no way to specify "no value" in the SKIRT configuration file mechanism. Even if you omit the attribute in the ski file, or leave it as the empty string, the SKIRT code internally still sees some default value (in the case of the new planar probes, a zero coordinate value). As a result, the default cut position is (0,0,0), corresponding to the position of the default cut probes. To get the same behaviour as your earlier planar probe version, you must explicitly specify the coordinates of the center of the spatial grid in the ski file. In other words, when you pull and build the new SKIRT version, you'll need to **manually adjust your ski file(s)**. Again, sorry for the inconvenience.

**Comment by christopherlovell** [comment]
@petercamps no problem, sorry I didn't get round to this.
