### ISSUE TITLE
Intrinsic luminosity across wavelengths with the SEDInstrument

### ISSUE THREAD

**Issue by kpolsen** [SKIRT/SKIRT9#22]
**Description**
This is a basic question about the interpretation of the SED being printed from SEDInstrument, since I seem to be overestimating the total luminosity of my test galaxy.

**Data**
I attach the stellar particle and medium files as well as the ski file used, in case it's something in the setup I'm doing wrong.

And here's the Python code used to derive luminosity from the SED output file:
```
data = pd.read_csv('skirt/'+ski_name+'_fo_sed.dat',skiprows=7,sep=' ',engine='python',\
    names=['wavelength','tot','trans','direct_primary','scattered_primary',\
   'direct_secondary','scattered_secondary'])
F_nu = data['tot'] # W/m^2 for all wavelengths
F_nu_tot = np.sum(F_nu) # W/m^2 summed over all wavelengths
distance = 10 # Mpc
kpc2m = 3.085677580666e19 # kpc in m
L_nu_W = F_nu_tot*4*np.pi*(distance*1e3*kpc2m)**2 # intrinsic luminosity over all wavelengths
print('%.2e W' % L_nu_W)
L_nu_sun = L_nu_W/L_sun
print('= %.2e Lsun' % L_nu_sun)
print('Current stellar mass for comparison: %.2e Msun' % (np.sum(star_df['m'])))
```
With output:
```
2.38e+41 W
= 6.19e+14 Lsun
Stellar mass for comparison: 9.58e+09 Msun
```

**System**
SKIRT9, Linux.

**Context**
I have the SED for my galaxy from 0.091 to 1000 micron in W/m^2 from the output of SEDInstrument:

![image](https://user-images.githubusercontent.com/13789517/66043512-a36bab00-e51f-11e9-956b-c77e48f4beaa.png)

(Note; Using variable smoothing lengths for the stars as discussed in [issue 10](https://github.com/SKIRT/SKIRT9/issues/10)). From that, I would like to calculate the total luminosity in solar units as a sanity check. However, when I sum up the above SED and integrate across a sphere with a radius equal to the distance of the instrument (10 Mpc), I get a very high luminosity of 6.19e+14 Lsun or 2.38e+48 ergs/s. For comparison the total current stellar mass is 9.58e+09 Msun.

I guess my questions are more specifically:
- am I using the distance parameter correctly here?
- is it correct that one can just sum up the SED to get luminosity when the “Neutral” flux output style is selected?

**Comment by petercamps** [comment]
@kpolsen I haven't looked into the details of your Python snippet, but I'll be happy to do so if the below comments don't resolve the issue for you.

To avoid unit conversions during tests like this, you can specify SI units in the configuration. Not sure why people use other units, but then I have an engineering background :-) 

The `LuminosityProbe` outputs the luminosity spectrum for the primary sources in your simulation. The second column lists the specific luminosity at each wavelength (W/m), and the third column lists the luminosity integrated over the bin (W). Assuming a sufficiently fine grid, summing the values of the third column yields the bolometric luminosity of the primary sources (i.e., the input luminosity). This can serve as a first check, and as a further reference for verifying the SED instrument results.

To integrate the spectrum produced by the SED instrument and convert it back into a luminosity it is best to use the `wavelength` flux units style, and also include the `InstrumentWavelengthGridProbe` in the configuration. This will give you a specific flux density in W/m2/m in the instrument output file, and a wavelength bin width in m in the wavelengths output file. Multiplying and summing these values performs the integration, and then multiplying by 4 pi d^2 (where d is in m) yields a luminosity in W.

Summing the `neutral` flux style values the way you propose does not work, because then you implicitly multiply each flux density value with the wavelength rather than the wavelength bin width. The units are correct, but the number is not.

A final caveat here is that the extinction in the UV/optical wavelength regime is not isotropic, so the received flux (and the derived bolometric luminosity value) depends on the viewing angle. You could do the calculation for an edge-on and face-on view, and if all goes well, these values should straddle the input luminosity.

Let me know if more clarification is needed (or something doesn't work).

**Comment by kpolsen** [comment]
@petercamps thank you for the quick reply!

It made sense - I tried both of the methods you suggest and get:
- 7.6726e+12 Lsun with `LuminosityProbe`
- 7.6717e+12 Lsun with `SEDInstrument`

consistent with the fact that the latter accounts for some extinction in the UV/optical as you say, and significantly lower than what I got before.

Follow-up questions: In the end I need the attenuated FUV flux for each cell, and I was planning on using `RadiationFieldPerCellProbe` for that. 
- 1. Is the output from `RadiationFieldPerCellProbe` attenuated by dust?
- 2. I have the radiation field intensities from `RadiationFieldPerCellProbe` set to units of "W/m2/micron/sr" (sorry, I'm an astronomer) - does that mean per m2 of the cell in question? 
- 3. Finally, to get the total luminosity would I multiply the radiation field intensities by wavelength bin size (in microns), area of each cell (volume^(2/3)) and 4 pi?

Doing iii. above gives me too high a luminosity compared to the previous methods, so I must be doing something wrong.

**Comment by petercamps** [comment]
@kpolsen Good to hear it works.

On your first question, the answer is **yes**. Indeed, calculating the attenuated radiation field is one of the main goals of SKIRT.

However, for your second and third questions, you cannot calculate a luminosity from the radiation field. The former measures how much radiation is emitted from a given region. The latter measures how much radiation passes through a given region, regardless of its origin. The two quantities are not related on a local scale.

Furthermore, SKIRT keeps track of the mean radiation field, without information on directionality. So you cannot calculate the flux through a given cell border without making the (usually unjustified) assumption of an isotropic radiation field. Even if you did make this assumption, summing these fluxes for all cell borders has no meaning.

You **can** calculate the absorbed power (luminosity) in each cell from the radiation field and the optical properties and density of the dust in the cell. That's what SKIRT does to calculate dust emission in each cell.

**Comment by kpolsen** [comment]
Oh right, that makes total sense. I'll try and make my future questions less basic but can't promise anything!

I will most likely be mapping the radiation field per cell to a new grid (btw, very happy to hear suggestions on how to do so) and I wanted a "check-sum" like total luminosity that I could compare before and after. Can one use the radiation field for that purpose? I.e. not summing the radiation field for the purpose of a luminosity, but to get at a **"total energy content"** that should be the same after mapping to a new grid?

**Comment by petercamps** [comment]
You could sum the product of mean intensity and cell volume for all wavelengths and for all cells (as in your point iii above but omitting the 2/3 exponent for the volume). This quantity would be proportional to the total absorbed energy assuming constant dust density and optical properties across the spatial domain, and should be invariant for regridding.

However, regridding is not necessarily trivial. One suggestion is to have SKIRT build a grid that you can use for your purposes to begin with. I'm closing this issue because this is too far from the original topic. If you'd like to further discuss regridding, I suggest opening another issue.
