### ISSUE TITLE
Question about SKIRT's multiple parallel processes

### ISSUE THREAD

**Issue by Celestemonde** [SKIRT/SKIRT9#224]
Hi, 

I am working on a batch of data obtained from hydrodynamic simulations and intend to import them into SKIRT for conducting further simulations. I've learned that SKIRT is capable of performing multiple simulations simultaneously. However, I'm not familiar with the specific commands involved. May I ask :

The organization of my files is:
<img width="321" alt="截圖 2024-11-15 14 12 52" src="https://github.com/user-attachments/assets/ad53c2bf-b36a-42e6-a979-6160a7828946">

The 'testmpi.ski' file is designed to run simulations on four folders names at specified numbers, which include both source and medium data. But I am not sure whether it is possible to run this ski file at one time for folders in the same directory. 

I have tried to place the ski file into each folder, and run SKIRT with command:

"$ skirt -t 4 -s 2 -r "~/Learn/test/*.ski" -k ",

(The command I used refers to: https://skirt.ugent.be/root/_user_cmd_line.html, https://skirt.ugent.be/root/_user_parallel.html）

which I specified 4 threads for each simulation, and 2 simulations to be executed in parallel. And this command appears to work. However, it requires placing a ski file in each of the data folders.

If I place a ski file in the same hierarchical directory as all the data folders (as shown in my picture), and then want each simulation to produce results in their respective folders, is such an operation possible?

Thank you in advance.

**Comment by petercamps** [comment]
Below are some comments and hopefully answers to your questions(s).

The `-k` option specifies that the input and output file paths are taken to be relative to the position of the ski file rather than the current directory from which the command is being executed. When combined with the `-r` option, this means that the input and output file paths will differ depending on where the ski file is positioned. In your example, you would need a copy of the ski file in each of the four given directories.

The `-s` option indeed allows to run multiple simulations in parallel in the same process but is mostly intended for testing purposes. I'd recommend one of the following approaches instead:

- Simply use all available threads in a single simulation, as long as the nr of threads is not too large.
- If there are too many threads to be efficient, you can use MPI to have multiple processes work on a single simulation.
- Alternatively you can launch multiple parallel instances of SKIRT by issuing more than one command at a time (use multiple terminals or put an & at the end of your bash command).

One option is to develop a Python procedure that launches the appropriate SKIRT instances. You can then provide the correct input/output paths with each invocation. You can use the functions in the PTS module simulation/skirt to invoke SKIRT. For a (quite advanced) example of how to run SKIRT instances in parallel, see the perform function in the PTS module test/functional. 

As an aside, note that having each simulation run in a separate SKIRT invocation makes things a bit more fail safe. If one simulation fails for some reason, the other processes simply keep on running.

**Comment by Celestemonde** [comment]
Thank you sincerely for your detailed reply! I will consult the related documents and try again.
