### ISSUE TITLE
Failure and uncertainties of MCRT in the IR?

### ISSUE THREAD

**Issue by mstalevski** [SKIRT/SKIRT9#58]
Related to the analysis of MCRT reliability at medium to high optical depths in Camps & Baes (2018), where you found that MCRT fails for tau > 75. This analysis is done by taking into account scattering and absorption in the optical. My question is if and how is this relevant for the results in the IR, where dust re-emission and self-absorption are the dominant processes? Specifically:

1) Does MCRT also fail in the IR and at which tau?

2) You say that the relative error, R, can be interpreted as flux uncertainty ("error bars") under certain conditions (R and VOV < 0.1). Again, is R defined in this way also meaningful in the IR?

**Comment by petercamps** [comment]
Interesting question. As long as we ignore the self-absorption process, the analysis and its results are fully independent of wavelength. In other words, everything is equally valid whether photon packets reach the SKIRT instruments from the primary sources (the very first emission phase) or from the secondary sources (the very last emission phase), and you can use SKIRT's `recordStatistics` flag to track the relevant statistics. Of course, the dust cross section changes with wavelength, but that just changes the optical depth, not the analysis.

The problem lies with the intermediate, iterative self-absorption phases. In these phases, the photon packets emitted by the dust never reach the instruments; they only serve to determine the adjusted radiation field in each cell until convergence is obtained. To apply a similar analysis, we would need to track the statistics for the contributions to the radiation field made by each photon packet. This is not implemented in SKIRT -- it would be possible but nontrivial, and it would slow the simulation down substantially.

As a workaround, one could get an idea of the number of photon packets needed in each self-absorption step by looking at the statistics of images produced by the last emission step for a number of relevant lines of sight and the shortest relevant dust emission wavelength. If these images have acceptable statistics for all areas, one might assume that a sufficient number of photon packets is being sent to reach all regions in the spatial domain. But one can never be sure, because this highly depends on the local geometry of the dust.

**Comment by mstalevski** [comment]
Got it, thanks, Peter.
