### ISSUE TITLE
segfault on exit with recordStatistics=true

### ISSUE THREAD

**Issue by dnelson86** [SKIRT/SKIRT9#91]
**Description**

A test case I am running completes successfully with recordStatistics == False for all the included instruments, but segfaults (after successful completion) with recordStatistics == True.

```
*** Error in `skirt': double free or corruption (out): 0x0000147d65ae3010 ***
05/03/2021 12:18:57.733   Welcome to SKIRT v9.0 (git 9691c88-dirty built on 02/12/2019 at 19:21:00)

05/03/2021 12:21:03.839 - Finished simulation sh343503 using 24 threads and a single process in 126 s (2m 6s).
terminate called after throwing an instance of 'FatalError'
```

**Reproduce**

Run the attached ski with attached input files.

**System**

intel 19.0.5
impi 2019.5

**Data**

[sh343503_gas_TNG100-1_95_fof=False_var_dtm_z.txt](https://github.com/SKIRT/SKIRT9/files/6090150/sh343503_gas_TNG100-1_95_fof.False_var_dtm_z.txt)

[sh343503_stars_TNG100-1_95_fof=False_fsps.txt](https://github.com/SKIRT/SKIRT9/files/6090156/sh343503_stars_TNG100-1_95_fof.False_fsps.txt)

[sh343503.ski.txt](https://github.com/SKIRT/SKIRT9/files/6090153/sh343503.ski.txt)

**Comment by petercamps** [comment]
Dylan,

Thank you for reporting this. I can reproduce the problem with a very simple configuration (a Plummer source, no medium and a single instrument) even when running on a single thread. The problem does not occur when compiled with Apple Clang, but it does occur with both Intel and GCC. The contents of the output files are identical, so it seems we can fully trust the results.

As you probably surmised, SKIRT crashes when it is destructing the data structures used for assembling the statistics. The `FluxRecorder` class uses a thread-local data member, implemented through a pretty intricate C++ template (if you're interested, see the `ThreadLocalMember` class template). Early versions of Apple Clang C++11 made things crash during construction (after my bug report, Apple fixed it in Apple Clang 10). This remaining problem may be in our code, since two compilers produce the same run-time error.

Fortunately the issue does not affect correct operation of the code, but still I'll try to look into it in more depth.
