### ISSUE TITLE
Matching a specific grain population

### ISSUE THREAD

**Issue by kpolsen** [SKIRT/SKIRT9#98]
**Description**
I'm using SKIRT in combination with Cloudy and I want to make sure that the dust model I select in each are as close to each other as possible. In Cloudy, I select **grains ISM**, for which Peter van Hoof provided me with the following information: 

> This consists of graphite and astronomical silicate (both: Martin & Rouleau 1991, in Extreme Ultraviolet Astronomy, eds. Malina & Bowyer, p. 341). The size distribution is a standard MRN power-law size distribution (Mathis J.S, Rumpl W., Nordsieck K.H., 1977, ApJ, 217, 425). The integrated volume for each component is 2.456864e-27 cm^3/H for graphite and 2.842704e-27 cm^3/H for silicate.

Have you thought about what might be a good match in SKIRT? I wonder if I'd get reasonably close to **grains ISM** with the ThemisDustMix or the WeingartnerDraineDustMix but I'm not sure how to test this? Or whether it might be easier to go the other way, and import the dust distribution parameters from Cloudy into SKIRT? 

**Data**
The exact size distribution and refractive index as function of wavelength used by Cloudy are stored in datafiles and one can create new datafiles with a specific distribution, if needed, but it's not completely straightforward. In particular, Cloudy needs both distributions on a very wide wavelength grid from gamma rays to radio. 

**System**
Not so relevant here I think.

**Context**
I use SKIRT to get attenuated FUV emission for further post-processing of galaxy simulations with the aim of simulating FIR lines. The FUV flux is one parameter of others passed on to Cloudy to calculate the line emission from the gas.

**Comment by mbaes** [comment]
SKIRT contains a [MRNDustMix](https://skirt.ugent.be/skirt9/class_m_r_n_dust_mix.html) class that has a standard MRN power-law size distribution, so I think this is a good starting point. It might be useful to dust properties of this model to the ones used in Cloudy.

**Comment by smartrittik** [comment]
I am using skirt to model smc and I am using Draines dust mixture so shall I give the default bin size for the dust mixture when asked for silicate and graphite which is 5 or something else , I mean I want to know what is this 5 bin size signifies

**Comment by petercamps** [comment]
The `numSilicateSizes` and `numGraphiteSizes` properties specify the number of bins used to discretize the grain size distribution for the silicate and graphite dust grain populations, respectively. If your simulation includes extinction only (no dust emission), these properties are not important and you can leave them at the default value of 5. However, if your simulation includes dust emission, then the discretization of the size distribution is important because the emission spectrum significantly depends on the grain size. Experience shows that a value of 15 bins for each grain type is sufficient to get accurate results. Also, in that case you need to set a `dustEmissionType` of `Stochastic` in the `DustEmissionOptions`.
